### ISSUE TITLE
Default driver selection wont work on "german" settings

### ISSUE THREAD

**Issue by herr-vogel** [TimSusa/cliptor#3]
On my Macbook the default driver name is "Standard - MacBook Pro Lautsprecher (Built-in)"
substr(10) doesn't work with "Standard", it leaves a space in the beginning

`'Standard - MacBook Pro Lautsprecher (Built-in).trim().substr(10) === '  MacBook Pro Lautsprecher (Built-in)'`

Maybe use `defaultDriver.split(' - ')[1]` ?

**Comment by TimSusa** [comment]
No problem, we can change this. I am not sure, how you wanna make it. Can you offer a small PR?
