### ISSUE TITLE
TimerClock still runs after stopping

### ISSUE THREAD

**Issue by herr-vogel** [TimSusa/cliptor#4]
What is the expected behaviour when you press the global stop button? 

Should the time stop and you can resume ? Or should it set to 0 and you start at the beginning?

Maybe use to buttons? Pause/Resume and Stop (sets the playback to the beginning)?

**Comment by herr-vogel** [comment]
quick fix would be `audioContext.suspend()` when you stop the tracks

**Comment by TimSusa** [comment]
Seems to work! Please have a look at https://github.com/TimSusa/cliptor/pull/6

**Comment by TimSusa** [comment]
As a base, we should consider to resume, stop and start the clock in file clock.js aswell. I think it would be helpful for more synchronization in between clip playback, if audiocontext time and thunk time are kind of the same.
